version: '3'
services:
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${FRONT_PORT}:3000
    volumes:
      - ./client:/app
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8000
    volumes:
      - ./api:/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      API_PORT: ${API_PORT}
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
